language: cpp

dist: focal

before_install:
  - sudo apt-get -y install qtbase5-dev libqt5svg5-dev
  - sudo apt-get -y install libocct-data-exchange-dev libocct-draw-dev

compiler:
  - gcc
  - clang

script:
  - chmod +x scripts/travis-build.sh
  - ./scripts/travis-build.sh
